const countryCodes = [
  "am-Am",
  "ar-AE",
  "ar-BH",
  "ar-DZ",
  "ar-EG",
  "ar-IQ",
  "ar-JO",
  "ar-KW",
  "ar-SA",
  "ar-SY",
  "ar-TN",
  "be-BY",
  "bg-BG",
  "bn-BD",
  "cs-CZ",
  "da-DK",
  "de-DE",
  "de-AT",
  "el-GR",
  "en-AU",
  "en-CA",
  "en-GB",
  "en-GG",
  "en-GH",
  "en-HK",
  "en-MO",
  "en-IE",
  "en-IN",
  "en-KE",
  "en-MT",
  "en-MU",
  "en-NG",
  "en-NZ",
  "en-PK",
  "en-RW",
  "en-SG",
  "en-SL",
  "en-UG",
  "en-US",
  "en-TZ",
  "en-ZA",
  "en-ZM",
  "es-CL",
  "es-CR",
  "es-EC",
  "es-ES",
  "es-MX",
  "es-PA",
  "es-PY",
  "es-UY",
  "et-EE",
  "fa-IR",
  "fi-FI",
  "fj-FJ",
  "fo-FO",
  "fr-BE",
  "fr-FR",
  "fr-GF",
  "fr-GP",
  "fr-MQ",
  "fr-RE",
  "he-IL",
  "hu-HU",
  "id-ID",
  "it-IT",
  "ja-JP",
  "kk-KZ",
  "kl-GL",
  "ko-KR",
  "lt-LT",
  "ms-MY",
  "nb-NO",
  "ne-NP",
  "nl-BE",
  "nl-NL",
  "nn-NO",
  "pl-PL",
  "pt-BR",
  "pt-PT",
  "ro-RO",
  "ru-RU",
  "sl-SI",
  "sk-SK",
  "sr-RS",
  "sv-SE",
  "th-TH",
  "tr-TR",
  "uk-UA",
  "vi-VN",
  "zh-CN",
  "zh-HK",
  "zh-MO",
  "zh-TW",
];

const countryListEN = {
  AE: "United Arab Emirates",
  AD: "Andorra",
  AL: "Albania",
  AM: "Armenia",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  AZ: "Azerbaijan",
  AX: "Åland Islands",
  BA: "Bosnia and Herzegovina",
  BD: "Bangladesh",
  BE: "Belgium",
  BH: "Bahrain",
  BO: "Bolivia",
  BY: "Belarus",
  CA: "Canada",
  CH: "Switzerland",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CZ: "Czech Republic",
  DK: "Denmark",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Georgia",
  GE: "Germany",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GL: "Greenland",
  GP: "Guadeloupe",
  GR: "Greece",
  HK: "Hong Kong",
  HN: "Honduras",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KZ: "Kazakhstan",
  LB: "Lebanon",
  LK: "Sri Lanka",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MG: "Madagascar",
  MK: "North Macedonia",
  ML: "Mali",
  MN: "Mongolia",
  MO: "Macau",
  MQ: "Martinique",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PT: "Portugal",
  PY: "Paraguay",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SI: "Slovenia",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SV: "El Salvador",
  SY: "Syria",
  SZ: "Eswatini",
  TH: "Thailand",
  TJ: "Tajikistan",
  TL: "Timor-Leste",
  TN: "Tunisia",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VE: "Venezuela",
  VN: "Vietnam",
  VU: "Vanuatu",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const countryListFA = {
  AD: "آندورا",
  AE: "امارات متحده عربی",
  AF: "افغانستان",
  AG: "آنتیگوا و باربودا",
  AI: "آنگویلا",
  AL: "آلبانی",
  AM: "ارمنستان",
  AO: "آنگولا",
  AQ: "جنوبگان",
  AR: "آرژانتین",
  AS: "ساموآی آمریکا",
  AT: "اتریش",
  AU: "استرالیا",
  AW: "آروبا",
  AX: "جزایر آلند",
  AZ: "جمهوری آذربایجان",
  BA: "بوسنی و هرزگوین",
  BB: "باربادوس",
  BD: "بنگلادش",
  BE: "بلژیک",
  BF: "بورکینا فاسو",
  BG: "بلغارستان",
  BH: "بحرین",
  BI: "بوروندی",
  BJ: "بنین",
  BL: "سنت بارثلمی",
  BM: "برمودا",
  BN: "برونئی",
  BO: "بولیوی",
  BQ: "هلند کارائیب",
  BR: "برزیل",
  BS: "باهاما",
  BT: "بوتان",
  BV: "جزیره بووه",
  BW: "بوتسوانا",
  BY: "بلاروس",
  BZ: "بلیز",
  CA: "کانادا",
  CC: "جزایر کوکوس",
  CD: "جمهوری دموکراتیک کنگو",
  CF: "جمهوری آفریقای مرکزی",
  CG: "جمهوری کنگو",
  CH: "سوئیس",
  CI: "ساحل عاج",
  CK: "جزایر کوک",
  CL: "شیلی",
  CM: "کامرون",
  CN: "چین",
  CO: "کلمبیا",
  CR: "کاستاریکا",
  CU: "کوبا",
  CV: "کیپ ورد",
  CW: "کوراسائو",
  CX: "جزیره کریسمس",
  CY: "قبرس",
  CZ: "جمهوری چک",
  DE: "آلمان",
  DJ: "جیبوتی",
  DK: "دانمارک",
  DM: "دومینیکا",
  DO: "دومینیکا",
  DZ: "الجزایر",
  EC: "اکوادور",
  EE: "استونی",
  EG: "مصر",
  EH: "صحرای غربی",
  ER: "اریتره",
  ES: "اسپانیا",
  ET: "اتیوپی",
  FI: "فنلاند",
  FJ: "فیجی",
  FK: "جزایر فالکلند",
  FM: "ایالات فدرال میکرونزی",
  FO: "جزایر فارو",
  FR: "فرانسه",
  GA: "گابن",
  GB: "انگلستان",
  GD: "گرانادا",
  GE: "گرجستان",
  GF: "گویان فرانسه",
  GG: "گرنزی",
  GH: "غنا",
  GI: "جبل الطارق",
  GL: "گرینلند",
  GM: "گامبیا",
  GN: "گینه",
  GP: "جزیره گوادلوپ",
  GQ: "گینه استوایی",
  GR: "یونان",
  GS: "جزایر جورجیای جنوبی و ساندویچ جنوبی",
  GT: "گواتمالا",
  GU: "گوام",
  GW: "گینه بیسائو",
  GY: "گویان",
  HK: "هنگ کنگ",
  HM: "جزیره هرد و جزایر مک دونالد",
  HN: "هندوراس",
  HR: "کرواسی",
  HT: "هائیتی",
  HU: "مجارستان",
  ID: "اندونزی",
  IE: "جمهوری ایرلند",
  IL: "فلسطین اشغالی (اسرائیل)",
  IM: "جزیره من",
  IN: "هند",
  IO: "قلمروی اقیانوس هند بریتانیا",
  IQ: "عراق",
  IR: "ایران",
  IS: "ایسلند",
  IT: "ایتالیا",
  JE: "ادبیات",
  JM: "جامائیکا",
  JO: "اردن",
  JP: "ژاپن",
  KE: "کنیا",
  KG: "قرقیزستان",
  KH: "کامبوج",
  KI: "کیریباتی",
  KM: "کومور",
  KN: "سنت کیتس و نویس",
  KP: "کره شمالی",
  KR: "کره جنوبی",
  KW: "کویت",
  KY: "جزایر کیمن",
  KZ: "قزاقستان",
  LA: "لائوس",
  LB: "لبنان",
  LC: "سنت لوسیا",
  LI: "لیختن اشتاین",
  LK: "سری لانکا",
  LR: "لیبریا",
  LS: "لسوتو",
  LT: "لیتوانی",
  LU: "لوکزامبورگ",
  LV: "لتونی",
  LY: "لیبی",
  MA: "مراکش",
  MC: "موناکو",
  MD: "مولداوی",
  ME: "مونته نگرو",
  MF: "سنت مارتین فرانسه",
  MG: "ماداگاسکار",
  MH: "جزایر مارشال",
  MK: "جمهوری مقدونیه",
  ML: "مالی",
  MM: "میانمار",
  MN: "مغولستان",
  MO: "ماکائو",
  MP: "جزایر ماریانای شمالی",
  MQ: "مارتینیک",
  MR: "موریتانی",
  MS: "مونتسرات",
  MT: "مالت",
  MU: "موریس",
  MV: "مالدیو",
  MW: "مالاوی",
  MX: "مکزیک",
  MY: "مالزی",
  MZ: "موزامبیک",
  NA: "نامیبیا",
  NC: "کالدونیای جدید",
  NE: "نیجر",
  NF: "جزیره نورفولک",
  NG: "نیجریه",
  NI: "نیکاراگوئه",
  NL: "هلند",
  NO: "نروژ",
  NP: "نپال",
  NR: "نائورو",
  NU: "نیوئه",
  NZ: "نیوزلند",
  OM: "عمان",
  PA: "پاناما",
  PE: "پرو",
  PF: "پلینزی فرانسه",
  PG: "پاپوآ گینه نو",
  PH: "فیلیپین",
  PK: "پاکستان",
  PL: "لهستان",
  PM: "سنت پیر و ماژلان",
  PN: "جزایر پیت‌کرن",
  PR: "پورتوریکو",
  PS: "فلسطین",
  PT: "پرتغال",
  PW: "پالائو",
  PY: "پاراگوئه",
  QA: "قطر",
  RE: "ریونیون",
  RO: "رومانی",
  RS: "صربستان",
  RU: "روسیه",
  RW: "رواندا",
  SA: "عربستان سعودی",
  SB: "جزایر سلیمان",
  SC: "سیشل",
  SD: "سودان",
  SE: "سوئد",
  SG: "سنگاپور",
  SH: "سینت هلینا",
  SI: "اسلوونی",
  SJ: "سوالبارد و یان ماین",
  SK: "اسلواکی",
  SL: "سیرالئون",
  SM: "سن مارینو",
  SN: "سنگال",
  SO: "سومالی",
  SR: "سورینام",
  ST: "سائوتومه و پرینسیپ",
  SV: "السالوادور",
  SX: "سنت مارتین هلند",
  SY: "سوریه",
  SZ: "سوازیلند",
  TC: "جزایر تورکس و کایکوس",
  TD: "چاد",
  TF: "سرزمین‌های قطب جنوب و جنوبی فرانسه",
  TG: "توگو",
  TH: "تایلند",
  TJ: "تاجیکستان",
  TK: "توکلائو",
  TL: "تیمور شرقی",
  TM: "ترکمنستان",
  TN: "تونس",
  TO: "تونگا",
  TR: "ترکیه",
  TT: "ترینیداد و توباگو",
  TV: "تووالو",
  TW: "تایوان",
  TZ: "تانزانیا",
  UA: "اوکراین",
  UG: "اوگاندا",
  UM: "جزایر کوچک حاشیه‌ای آمریکا",
  US: "ایالات متحده",
  UY: "اروگوئه",
  UZ: "ازبکستان",
  VA: "شهر واتیکان",
  VC: "سنت وینسنت و گرنادین",
  VE: "ونزوئلا",
  VG: "جزایر ویرجین بریتانیا",
  VI: "جزایر ویرجین ایالات متحده آمریکا",
  VN: "ویتنام",
  VU: "وانواتو",
  WF: "والیس و فوتونا",
  WS: "ساموآ",
  YE: "یمن",
  YT: "مایوت",
  ZA: "آفریقای جنوبی",
  ZM: "زامبیا",
  ZW: "زیمبابوه",
};

const PhoneLocale = {
  AM: "am-AM",
  AE: "ar-AE",
  BH: "ar-BH",
  DZ: "ar-DZ",
  LB: "ar-LB",
  EG: "ar-EG",
  IQ: "ar-IQ",
  JO: "ar-JO",
  KW: "ar-KW",
  LY: "ar-LY",
  MA: "ar-MA",
  OM: "ar-OM",
  SA: "ar-SA",
  SY: "ar-SY",
  TN: "ar-TN",
  AZ: "az-AZ",
  BA: "bs-BA",
  BY: "be-BY",
  BG: "bg-BG",
  BD: "bn-BD",
  CA: "ca-AD",
  CZ: "cs-CZ",
  DK: "da-DK",
  DE: "de-DE",
  AT: "de-AT",
  CH: "de-CH",
  LU: "de-LU",
  GR: "el-GR",
  AU: "en-AU",
  GB: "en-GB",
  GG: "en-GG",
  GH: "en-GH",
  HK: "en-HK",
  MO: "en-MO",
  IE: "en-IE",
  IN: "en-IN",
  KE: "en-KE",
  MT: "en-MT",
  MU: "en-MU",
  NG: "en-NG",
  NZ: "en-NZ",
  PK: "en-PK",
  PH: "en-PH",
  RW: "en-RW",
  SG: "en-SG",
  SL: "en-SL",
  TZ: "en-TZ",
  UG: "en-UG",
  US: "en-US",
  ZA: "en-ZA",
  ZM: "en-ZM",
  ZW: "en-ZW",
  AR: "es-AR",
  BO: "es-BO",
  CO: "es-CO",
  CL: "es-CL",
  CR: "es-CR",
  DO: "es-DO",
  HN: "es-HN",
  EC: "es-EC",
  ES: "es-ES",
  PE: "es-PE",
  MX: "es-MX",
  PA: "es-PA",
  PY: "es-PY",
  UY: "es-UY",
  VE: "es-VE",
  EE: "et-EE",
  IR: "fa-IR",
  FI: "fi-FI",
  FJ: "fj-FJ",
  FO: "fo-FO",
  FR: "fr-FR",
  GF: "fr-GF",
  GP: "fr-GP",
  MQ: "fr-MQ",
  RE: "fr-RE",
  IL: "he-IL",
  HU: "hu-HU",
  ID: "id-ID",
  IT: "it-IT",
  SM: "it-SM",
  JP: "ja-JP",
  GE: "ka-GE",
  KZ: "kk-KZ",
  GL: "kl-GL",
  KR: "ko-KR",
  LT: "lt-LT",
  LV: "lv-LV",
  MY: "ms-MY",
  MZ: "mz-MZ",
  NO: "nn-NO",
  NP: "ne-NP",
  BE: "nl-BE",
  NL: "nl-NL",
  PL: "pl-PL",
  BR: "pt-BR",
  PT: "pt-PT",
  AO: "pt-AO",
  RO: "ro-RO",
  RU: "ru-RU",
  LK: "i-LK",
  SI: "l-SI",
  SK: "k-SK",
  AL: "q-AL",
  RS: "r-RS",
  SE: "v-SE",
  TH: "th-TH",
  TR: "tr-TR",
  UA: "uk-UA",
  UZ: "uz-UZ",
  VN: "vi-VN",
  CN: "zh-CN",
  TW: "zh-TW",
};

const countryPhoneCodes = {
  AF: "+93",
  AL: "+355",
  DZ: "+213",
  AS: "+1 684",
  AD: "+376",
  AO: "+244",
  AI: "+1 264",
  AQ: "+672",
  AG: "+1 268",
  AR: "+54",
  AM: "+374",
  AW: "+297",
  AU: "+61",
  AT: "+43",
  AZ: "+994",
  BS: "+1 242",
  BH: "+973",
  BD: "+880",
  BB: "+1 246",
  BY: "+375",
  BE: "+32",
  BZ: "+501",
  BJ: "+229",
  BM: "+1 441",
  BT: "+975",
  BO: "+591",
  BA: "+387",
  BW: "+267",
  BR: "+55",
  IO: "+246",
  VG: "+1 284",
  BN: "+673",
  BG: "+359",
  BF: "+226",
  BI: "+257",
  KH: "+855",
  CM: "+237",
  CA: "+1",
  CV: "+238",
  KY: "+1 345",
  CF: "+236",
  CL: "+56",
  CN: "+86",
  CX: "+61",
  CC: "+61",
  CO: "+57",
  KM: "+269",
  CG: "+242",
  CD: "+243",
  CK: "+682",
  CR: "+506",
  CI: "+225",
  HR: "+385",
  CU: "+53",
  CW: "+599",
  CY: "+357",
  CZ: "+420",
  DK: "+45",
  DJ: "+253",
  DM: "+1 767",
  DO: "+1 809",
  EC: "+593",
  EG: "+20",
  GQ: "+240",
  ER: "+291",
  EE: "+372",
  ET: "+251",
  FK: "+500",
  FO: "+298",
  FJ: "+679",
  FI: "+358",
  FR: "+33",
  GF: "+594",
  PF: "+689",
  GA: "+241",
  GM: "+220",
  GE: "+995",
  DE: "+49",
  GH: "+233",
  GI: "+350",
  GR: "+30",
  GL: "+299",
  GD: "+1 473",
  GP: "+590",
  GU: "+1 671",
  GT: "+502",
  GG: "+44",
  GN: "+224",
  GW: "+245",
  GY: "+592",
  HT: "+509",
  HN: "+504",
  HK: "+852",
  HU: "+36",
  IS: "+354",
  IN: "+91",
  ID: "+62",
  IR: "+98",
  IQ: "+964",
  IE: "+353",
  IL: "+972",
  IT: "+39",
  JM: "+1 876",
  JP: "+81",
  JE: "+44",
  JO: "+962",
  KZ: "+7",
  KE: "+254",
  KI: "+686",
  KP: "+850",
  KR: "+82",
  KW: "+965",
  KG: "+996",
  LA: "+856",
  LV: "+371",
  LB: "+961",
  LS: "+266",
  LR: "+231",
  LY: "+218",
  LT: "+370",
  LU: "+352",
  MO: "+853",
  MK: "+389",
  MG: "+261",
  MW: "+265",
  MY: "+60",
  MV: "+960",
  ML: "+223",
  MT: "+356",
  MH: "+692",
  MQ: "+596",
  MR: "+222",
  MU: "+230",
  YT: "+262",
  MX: "+52",
  FM: "+691",
  MD: "+373",
  MC: "+377",
  MN: "+976",
  ME: "+382",
  MS: "+1 664",
  MA: "+212",
  MZ: "+258",
  MM: "+95",
  NA: "+264",
  NR: "+674",
  NP: "+977",
  NL: "+31",
  NC: "+687",
  NZ: "+64",
  NI: "+505",
  NE: "+227",
  NG: "+234",
  NU: "+683",
  NF: "+672",
  MP: "+1 670",
  NO: "+47",
  OM: "+968",
  PK: "+92",
  PW: "+680",
  PS: "+970",
  PA: "+507",
  PG: "+675",
  PY: "+595",
  PE: "+51",
  PH: "+63",
  PN: "+872",
  PL: "+48",
  PT: "+351",
  PR: "+1 787",
  QA: "+974",
  RE: "+262",
  RO: "+40",
  RU: "+7",
  RW: "+250",
  SA: "+966",
  SB: "+677",
  SC: "+248",
  SD: "+249",
  SE: "+46",
  SG: "+65",
  SH: "+290",
  SI: "+386",
  SJ: "+47",
  SK: "+421",
  SL: "+232",
  SM: "+378",
  SN: "+221",
  SO: "+252",
  SR: "+597",
  ST: "+239",
  SV: "+503",
  SY: "+963",
  SZ: "+268",
  TC: "+1 649",
  TD: "+235",
  TF: "+262",
  TG: "+228",
  TH: "+66",
  TJ: "+992",
  TK: "+690",
  TL: "+670",
  TM: "+993",
  TN: "+216",
  TO: "+676",
  TR: "+90",
  TT: "+1 868",
  TV: "+688",
  TW: "+886",
  TZ: "+255",
  UA: "+380",
  UG: "+256",
  US: "+1",
  UY: "+598",
  UZ: "+998",
  VA: "+379",
  VC: "+1 784",
  VE: "+58",
  VI: "+1 340",
  VN: "+84",
  VU: "+678",
  WF: "+681",
  WS: "+685",
  YE: "+967",
  ZA: "+27",
  ZM: "+260",
  ZW: "+263",
};

const countries = [
    {
        "fa": "امارات متحده عربی",
        "en": "United Arab Emirates",
        "isoCode": "ar-AE",
        "code": "AE"
    },
    {
        "fa": "آندورا",
        "en": "Andorra",
        "phoneCode": "+376",
        "code": "AD"
    },
    {
        "fa": "آلبانی",
        "en": "Albania",
        "isoCode": "q-AL",
        "phoneCode": "+355",
        "code": "AL"
    },
    {
        "fa": "ارمنستان",
        "en": "Armenia",
        "isoCode": "am-AM",
        "phoneCode": "+374",
        "code": "AM"
    },
    {
        "fa": "آرژانتین",
        "en": "Argentina",
        "isoCode": "es-AR",
        "phoneCode": "+54",
        "code": "AR"
    },
    {
        "fa": "اتریش",
        "en": "Austria",
        "isoCode": "de-AT",
        "phoneCode": "+43",
        "code": "AT"
    },
    {
        "fa": "استرالیا",
        "en": "Australia",
        "isoCode": "en-AU",
        "phoneCode": "+61",
        "code": "AU"
    },
    {
        "fa": "جمهوری آذربایجان",
        "en": "Azerbaijan",
        "isoCode": "az-AZ",
        "phoneCode": "+994",
        "code": "AZ"
    },
    {
        "fa": "جزایر آلند",
        "en": "Åland Islands",
        "code": "AX"
    },
    {
        "fa": "بوسنی و هرزگوین",
        "en": "Bosnia and Herzegovina",
        "isoCode": "bs-BA",
        "phoneCode": "+387",
        "code": "BA"
    },
    {
        "fa": "بنگلادش",
        "en": "Bangladesh",
        "isoCode": "bn-BD",
        "phoneCode": "+880",
        "code": "BD"
    },
    {
        "fa": "بلژیک",
        "en": "Belgium",
        "isoCode": "nl-BE",
        "phoneCode": "+32",
        "code": "BE"
    },
    {
        "fa": "بحرین",
        "en": "Bahrain",
        "isoCode": "ar-BH",
        "phoneCode": "+973",
        "code": "BH"
    },
    {
        "fa": "بولیوی",
        "en": "Bolivia",
        "isoCode": "es-BO",
        "phoneCode": "+591",
        "code": "BO"
    },
    {
        "fa": "بلاروس",
        "en": "Belarus",
        "isoCode": "be-BY",
        "phoneCode": "+375",
        "code": "BY"
    },
    {
        "fa": "کانادا",
        "en": "Canada",
        "isoCode": "ca-AD",
        "phoneCode": "+1",
        "code": "CA"
    },
    {
        "fa": "سوئیس",
        "en": "Switzerland",
        "isoCode": "de-CH",
        "code": "CH"
    },
    {
        "fa": "شیلی",
        "en": "Chile",
        "isoCode": "es-CL",
        "phoneCode": "+56",
        "code": "CL"
    },
    {
        "fa": "چین",
        "en": "China",
        "isoCode": "zh-CN",
        "phoneCode": "+86",
        "code": "CN"
    },
    {
        "fa": "کلمبیا",
        "en": "Colombia",
        "isoCode": "es-CO",
        "phoneCode": "+57",
        "code": "CO"
    },
    {
        "fa": "کاستاریکا",
        "en": "Costa Rica",
        "isoCode": "es-CR",
        "phoneCode": "+506",
        "code": "CR"
    },
    {
        "fa": "جمهوری چک",
        "en": "Czech Republic",
        "isoCode": "cs-CZ",
        "phoneCode": "+420",
        "code": "CZ"
    },
    {
        "fa": "دانمارک",
        "en": "Denmark",
        "isoCode": "da-DK",
        "phoneCode": "+45",
        "code": "DK"
    },
    {
        "fa": "دومینیکا",
        "en": "Dominican Republic",
        "isoCode": "es-DO",
        "phoneCode": "+1 809",
        "code": "DO"
    },
    {
        "fa": "الجزایر",
        "en": "Algeria",
        "isoCode": "ar-DZ",
        "phoneCode": "+213",
        "code": "DZ"
    },
    {
        "fa": "اکوادور",
        "en": "Ecuador",
        "isoCode": "es-EC",
        "phoneCode": "+593",
        "code": "EC"
    },
    {
        "fa": "استونی",
        "en": "Estonia",
        "isoCode": "et-EE",
        "phoneCode": "+372",
        "code": "EE"
    },
    {
        "fa": "مصر",
        "en": "Egypt",
        "isoCode": "ar-EG",
        "phoneCode": "+20",
        "code": "EG"
    },
    {
        "fa": "اسپانیا",
        "en": "Spain",
        "isoCode": "es-ES",
        "code": "ES"
    },
    {
        "fa": "اتیوپی",
        "en": "Ethiopia",
        "phoneCode": "+251",
        "code": "ET"
    },
    {
        "fa": "فنلاند",
        "en": "Finland",
        "isoCode": "fi-FI",
        "phoneCode": "+358",
        "code": "FI"
    },
    {
        "fa": "فیجی",
        "en": "Fiji",
        "isoCode": "fj-FJ",
        "phoneCode": "+679",
        "code": "FJ"
    },
    {
        "fa": "جزایر فارو",
        "en": "Faroe Islands",
        "isoCode": "fo-FO",
        "phoneCode": "+298",
        "code": "FO"
    },
    {
        "fa": "فرانسه",
        "en": "France",
        "isoCode": "fr-FR",
        "phoneCode": "+33",
        "code": "FR"
    },
    {
        "fa": "گابن",
        "en": "Georgia",
        "phoneCode": "+241",
        "code": "GA"
    },
    {
        "fa": "گرجستان",
        "en": "Germany",
        "isoCode": "ka-GE",
        "phoneCode": "+995",
        "code": "GE"
    },
    {
        "fa": "گویان فرانسه",
        "en": "French Guiana",
        "isoCode": "fr-GF",
        "phoneCode": "+594",
        "code": "GF"
    },
    {
        "fa": "گرنزی",
        "en": "Guernsey",
        "isoCode": "en-GG",
        "phoneCode": "+44",
        "code": "GG"
    },
    {
        "fa": "غنا",
        "en": "Ghana",
        "isoCode": "en-GH",
        "phoneCode": "+233",
        "code": "GH"
    },
    {
        "fa": "گرینلند",
        "en": "Greenland",
        "isoCode": "kl-GL",
        "phoneCode": "+299",
        "code": "GL"
    },
    {
        "fa": "جزیره گوادلوپ",
        "en": "Guadeloupe",
        "isoCode": "fr-GP",
        "phoneCode": "+590",
        "code": "GP"
    },
    {
        "fa": "یونان",
        "en": "Greece",
        "isoCode": "el-GR",
        "phoneCode": "+30",
        "code": "GR"
    },
    {
        "fa": "هنگ کنگ",
        "en": "Hong Kong",
        "isoCode": "en-HK",
        "phoneCode": "+852",
        "code": "HK"
    },
    {
        "fa": "هندوراس",
        "en": "Honduras",
        "isoCode": "es-HN",
        "phoneCode": "+504",
        "code": "HN"
    },
    {
        "fa": "مجارستان",
        "en": "Hungary",
        "isoCode": "hu-HU",
        "phoneCode": "+36",
        "code": "HU"
    },
    {
        "fa": "اندونزی",
        "en": "Indonesia",
        "isoCode": "id-ID",
        "phoneCode": "+62",
        "code": "ID"
    },
    {
        "fa": "جمهوری ایرلند",
        "en": "Ireland",
        "isoCode": "en-IE",
        "phoneCode": "+353",
        "code": "IE"
    },
    {
        "fa": "فلسطین اشغالی (اسرائیل)",
        "en": "Israel",
        "isoCode": "he-IL",
        "phoneCode": "+972",
        "code": "IL"
    },
    {
        "fa": "هند",
        "en": "India",
        "isoCode": "en-IN",
        "phoneCode": "+91",
        "code": "IN"
    },
    {
        "fa": "عراق",
        "en": "Iraq",
        "isoCode": "ar-IQ",
        "phoneCode": "+964",
        "code": "IQ"
    },
    {
        "fa": "ایران",
        "en": "Iran",
        "isoCode": "fa-IR",
        "phoneCode": "+98",
        "code": "IR"
    },
    {
        "fa": "ایسلند",
        "en": "Iceland",
        "phoneCode": "+354",
        "code": "IS"
    },
    {
        "fa": "ایتالیا",
        "en": "Italy",
        "isoCode": "it-IT",
        "phoneCode": "+39",
        "code": "IT"
    },
    {
        "fa": "اردن",
        "en": "Jordan",
        "isoCode": "ar-JO",
        "phoneCode": "+962",
        "code": "JO"
    },
    {
        "fa": "ژاپن",
        "en": "Japan",
        "isoCode": "ja-JP",
        "phoneCode": "+81",
        "code": "JP"
    },
    {
        "fa": "کنیا",
        "en": "Kenya",
        "isoCode": "en-KE",
        "phoneCode": "+254",
        "code": "KE"
    },
    {
        "fa": "قرقیزستان",
        "en": "Kyrgyzstan",
        "phoneCode": "+996",
        "code": "KG"
    },
    {
        "fa": "کامبوج",
        "en": "Cambodia",
        "phoneCode": "+855",
        "code": "KH"
    },
    {
        "fa": "کیریباتی",
        "en": "Kiribati",
        "phoneCode": "+686",
        "code": "KI"
    },
    {
        "fa": "کومور",
        "en": "Comoros",
        "phoneCode": "+269",
        "code": "KM"
    },
    {
        "fa": "سنت کیتس و نویس",
        "en": "Saint Kitts and Nevis",
        "code": "KN"
    },
    {
        "fa": "کره شمالی",
        "en": "North Korea",
        "phoneCode": "+850",
        "code": "KP"
    },
    {
        "fa": "کره جنوبی",
        "en": "South Korea",
        "isoCode": "ko-KR",
        "phoneCode": "+82",
        "code": "KR"
    },
    {
        "fa": "کویت",
        "en": "Kuwait",
        "isoCode": "ar-KW",
        "phoneCode": "+965",
        "code": "KW"
    },
    {
        "fa": "قزاقستان",
        "en": "Kazakhstan",
        "isoCode": "kk-KZ",
        "phoneCode": "+7",
        "code": "KZ"
    },
    {
        "fa": "لبنان",
        "en": "Lebanon",
        "isoCode": "ar-LB",
        "phoneCode": "+961",
        "code": "LB"
    },
    {
        "fa": "سری لانکا",
        "en": "Sri Lanka",
        "isoCode": "i-LK",
        "code": "LK"
    },
    {
        "fa": "لیتوانی",
        "en": "Lithuania",
        "isoCode": "lt-LT",
        "phoneCode": "+370",
        "code": "LT"
    },
    {
        "fa": "لوکزامبورگ",
        "en": "Luxembourg",
        "isoCode": "de-LU",
        "phoneCode": "+352",
        "code": "LU"
    },
    {
        "fa": "لتونی",
        "en": "Latvia",
        "isoCode": "lv-LV",
        "phoneCode": "+371",
        "code": "LV"
    },
    {
        "fa": "لیبی",
        "en": "Libya",
        "isoCode": "ar-LY",
        "phoneCode": "+218",
        "code": "LY"
    },
    {
        "fa": "مراکش",
        "en": "Morocco",
        "isoCode": "ar-MA",
        "phoneCode": "+212",
        "code": "MA"
    },
    {
        "fa": "موناکو",
        "en": "Monaco",
        "phoneCode": "+377",
        "code": "MC"
    },
    {
        "fa": "مولداوی",
        "en": "Moldova",
        "phoneCode": "+373",
        "code": "MD"
    },
    {
        "fa": "مونته نگرو",
        "en": "Montenegro",
        "phoneCode": "+382",
        "code": "ME"
    },
    {
        "fa": "ماداگاسکار",
        "en": "Madagascar",
        "phoneCode": "+261",
        "code": "MG"
    },
    {
        "fa": "جمهوری مقدونیه",
        "en": "North Macedonia",
        "phoneCode": "+389",
        "code": "MK"
    },
    {
        "fa": "مالی",
        "en": "Mali",
        "phoneCode": "+223",
        "code": "ML"
    },
    {
        "fa": "مغولستان",
        "en": "Mongolia",
        "phoneCode": "+976",
        "code": "MN"
    },
    {
        "fa": "ماکائو",
        "en": "Macau",
        "isoCode": "en-MO",
        "phoneCode": "+853",
        "code": "MO"
    },
    {
        "fa": "مارتینیک",
        "en": "Martinique",
        "isoCode": "fr-MQ",
        "phoneCode": "+596",
        "code": "MQ"
    },
    {
        "fa": "مالت",
        "en": "Malta",
        "isoCode": "en-MT",
        "phoneCode": "+356",
        "code": "MT"
    },
    {
        "fa": "موریس",
        "en": "Mauritius",
        "isoCode": "en-MU",
        "phoneCode": "+230",
        "code": "MU"
    },
    {
        "fa": "مالدیو",
        "en": "Maldives",
        "phoneCode": "+960",
        "code": "MV"
    },
    {
        "fa": "مالاوی",
        "en": "Malawi",
        "phoneCode": "+265",
        "code": "MW"
    },
    {
        "fa": "مکزیک",
        "en": "Mexico",
        "isoCode": "es-MX",
        "phoneCode": "+52",
        "code": "MX"
    },
    {
        "fa": "مالزی",
        "en": "Malaysia",
        "isoCode": "ms-MY",
        "phoneCode": "+60",
        "code": "MY"
    },
    {
        "fa": "موزامبیک",
        "en": "Mozambique",
        "isoCode": "mz-MZ",
        "phoneCode": "+258",
        "code": "MZ"
    },
    {
        "fa": "نامیبیا",
        "en": "Namibia",
        "phoneCode": "+264",
        "code": "NA"
    },
    {
        "fa": "نیجریه",
        "en": "Nigeria",
        "isoCode": "en-NG",
        "phoneCode": "+234",
        "code": "NG"
    },
    {
        "fa": "نیکاراگوئه",
        "en": "Nicaragua",
        "phoneCode": "+505",
        "code": "NI"
    },
    {
        "fa": "هلند",
        "en": "Netherlands",
        "isoCode": "nl-NL",
        "phoneCode": "+31",
        "code": "NL"
    },
    {
        "fa": "نروژ",
        "en": "Norway",
        "isoCode": "nn-NO",
        "phoneCode": "+47",
        "code": "NO"
    },
    {
        "fa": "نپال",
        "en": "Nepal",
        "isoCode": "ne-NP",
        "phoneCode": "+977",
        "code": "NP"
    },
    {
        "fa": "نیوزلند",
        "en": "New Zealand",
        "isoCode": "en-NZ",
        "phoneCode": "+64",
        "code": "NZ"
    },
    {
        "fa": "عمان",
        "en": "Oman",
        "isoCode": "ar-OM",
        "phoneCode": "+968",
        "code": "OM"
    },
    {
        "fa": "پاناما",
        "en": "Panama",
        "isoCode": "es-PA",
        "phoneCode": "+507",
        "code": "PA"
    },
    {
        "fa": "پرو",
        "en": "Peru",
        "isoCode": "es-PE",
        "phoneCode": "+51",
        "code": "PE"
    },
    {
        "fa": "فیلیپین",
        "en": "Philippines",
        "isoCode": "en-PH",
        "phoneCode": "+63",
        "code": "PH"
    },
    {
        "fa": "پاکستان",
        "en": "Pakistan",
        "isoCode": "en-PK",
        "phoneCode": "+92",
        "code": "PK"
    },
    {
        "fa": "لهستان",
        "en": "Poland",
        "isoCode": "pl-PL",
        "phoneCode": "+48",
        "code": "PL"
    },
    {
        "fa": "پرتغال",
        "en": "Portugal",
        "isoCode": "pt-PT",
        "phoneCode": "+351",
        "code": "PT"
    },
    {
        "fa": "پاراگوئه",
        "en": "Paraguay",
        "isoCode": "es-PY",
        "phoneCode": "+595",
        "code": "PY"
    },
    {
        "fa": "ریونیون",
        "en": "Réunion",
        "isoCode": "fr-RE",
        "phoneCode": "+262",
        "code": "RE"
    },
    {
        "fa": "رومانی",
        "en": "Romania",
        "isoCode": "ro-RO",
        "phoneCode": "+40",
        "code": "RO"
    },
    {
        "fa": "صربستان",
        "en": "Serbia",
        "isoCode": "r-RS",
        "code": "RS"
    },
    {
        "fa": "روسیه",
        "en": "Russia",
        "isoCode": "ru-RU",
        "phoneCode": "+7",
        "code": "RU"
    },
    {
        "fa": "رواندا",
        "en": "Rwanda",
        "isoCode": "en-RW",
        "phoneCode": "+250",
        "code": "RW"
    },
    {
        "fa": "عربستان سعودی",
        "en": "Saudi Arabia",
        "isoCode": "ar-SA",
        "phoneCode": "+966",
        "code": "SA"
    },
    {
        "fa": "جزایر سلیمان",
        "en": "Solomon Islands",
        "phoneCode": "+677",
        "code": "SB"
    },
    {
        "fa": "سیشل",
        "en": "Seychelles",
        "phoneCode": "+248",
        "code": "SC"
    },
    {
        "fa": "سودان",
        "en": "Sudan",
        "phoneCode": "+249",
        "code": "SD"
    },
    {
        "fa": "سوئد",
        "en": "Sweden",
        "isoCode": "v-SE",
        "phoneCode": "+46",
        "code": "SE"
    },
    {
        "fa": "سنگاپور",
        "en": "Singapore",
        "isoCode": "en-SG",
        "phoneCode": "+65",
        "code": "SG"
    },
    {
        "fa": "اسلوونی",
        "en": "Slovenia",
        "isoCode": "l-SI",
        "phoneCode": "+386",
        "code": "SI"
    },
    {
        "fa": "اسلواکی",
        "en": "Slovakia",
        "isoCode": "k-SK",
        "phoneCode": "+421",
        "code": "SK"
    },
    {
        "fa": "سیرالئون",
        "en": "Sierra Leone",
        "isoCode": "en-SL",
        "phoneCode": "+232",
        "code": "SL"
    },
    {
        "fa": "سن مارینو",
        "en": "San Marino",
        "isoCode": "it-SM",
        "phoneCode": "+378",
        "code": "SM"
    },
    {
        "fa": "سنگال",
        "en": "Senegal",
        "phoneCode": "+221",
        "code": "SN"
    },
    {
        "fa": "سومالی",
        "en": "Somalia",
        "phoneCode": "+252",
        "code": "SO"
    },
    {
        "fa": "سورینام",
        "en": "Suriname",
        "phoneCode": "+597",
        "code": "SR"
    },
    {
        "fa": "السالوادور",
        "en": "El Salvador",
        "phoneCode": "+503",
        "code": "SV"
    },
    {
        "fa": "سوریه",
        "en": "Syria",
        "isoCode": "ar-SY",
        "phoneCode": "+963",
        "code": "SY"
    },
    {
        "fa": "سوازیلند",
        "en": "Eswatini",
        "phoneCode": "+268",
        "code": "SZ"
    },
    {
        "fa": "تایلند",
        "en": "Thailand",
        "isoCode": "th-TH",
        "phoneCode": "+66",
        "code": "TH"
    },
    {
        "fa": "تاجیکستان",
        "en": "Tajikistan",
        "phoneCode": "+992",
        "code": "TJ"
    },
    {
        "fa": "تیمور شرقی",
        "en": "Timor-Leste",
        "phoneCode": "+670",
        "code": "TL"
    },
    {
        "fa": "تونس",
        "en": "Tunisia",
        "isoCode": "ar-TN",
        "phoneCode": "+216",
        "code": "TN"
    },
    {
        "fa": "ترکیه",
        "en": "Turkey",
        "isoCode": "tr-TR",
        "phoneCode": "+90",
        "code": "TR"
    },
    {
        "fa": "ترینیداد و توباگو",
        "en": "Trinidad and Tobago",
        "phoneCode": "+1 868",
        "code": "TT"
    },
    {
        "fa": "تایوان",
        "en": "Taiwan",
        "isoCode": "zh-TW",
        "phoneCode": "+886",
        "code": "TW"
    },
    {
        "fa": "تانزانیا",
        "en": "Tanzania",
        "isoCode": "en-TZ",
        "phoneCode": "+255",
        "code": "TZ"
    },
    {
        "fa": "اوکراین",
        "en": "Ukraine",
        "isoCode": "uk-UA",
        "phoneCode": "+380",
        "code": "UA"
    },
    {
        "fa": "اوگاندا",
        "en": "Uganda",
        "isoCode": "en-UG",
        "phoneCode": "+256",
        "code": "UG"
    },
    {
        "fa": "ایالات متحده",
        "en": "United States",
        "isoCode": "en-US",
        "phoneCode": "+1",
        "code": "US"
    },
    {
        "fa": "اروگوئه",
        "en": "Uruguay",
        "isoCode": "es-UY",
        "phoneCode": "+598",
        "code": "UY"
    },
    {
        "fa": "ازبکستان",
        "en": "Uzbekistan",
        "isoCode": "uz-UZ",
        "phoneCode": "+998",
        "code": "UZ"
    },
    {
        "fa": "شهر واتیکان",
        "en": "Vatican City",
        "phoneCode": "+379",
        "code": "VA"
    },
    {
        "fa": "ونزوئلا",
        "en": "Venezuela",
        "isoCode": "es-VE",
        "phoneCode": "+58",
        "code": "VE"
    },
    {
        "fa": "ویتنام",
        "en": "Vietnam",
        "isoCode": "vi-VN",
        "phoneCode": "+84",
        "code": "VN"
    },
    {
        "fa": "وانواتو",
        "en": "Vanuatu",
        "phoneCode": "+678",
        "code": "VU"
    },
    {
        "fa": "آفریقای جنوبی",
        "en": "South Africa",
        "isoCode": "en-ZA",
        "phoneCode": "+27",
        "code": "ZA"
    },
    {
        "fa": "زامبیا",
        "en": "Zambia",
        "isoCode": "en-ZM",
        "phoneCode": "+260",
        "code": "ZM"
    },
    {
        "fa": "زیمبابوه",
        "en": "Zimbabwe",
        "isoCode": "en-ZW",
        "phoneCode": "+263",
        "code": "ZW"
    }
];
